.TH ff-attributes 7 "2020-06-06" "Version 566" "ff Plugin Attributes Reference"
.nh
.SH DESCRIPTION
This is a list of all attributes that are available. Attributes are provided by plugins. For more details use \fBff \fB\-\-help\fP <plugin>\fP.

.SH FILE PLUGIN

.SS Description
The "file" plugin provides all essential file attributes. Among these attributes are variations of the file's path name (e.g. dirname, basename, extension) and inode information from \fBstat\fP(2) (e.g. file size, file type, modification time). The leading '\fIfile.\fP' part is optional and can be omitted.

.SS Attributes
.IP "\fB[file.]path\fP" 4
Type: path ( = : ~ % )
.br
The full pathname of the file. It will be relative to the current working directory depending on the <directory> arguments that were given on the command line. This can be changed with the \fB\-a\fP/\fB\-\-absolute\fP path option.

.IP "\fB[file.]root\fP" 4
Type: path ( = : ~ % )
.br
The start directory the file was found in.

.IP "\fB[file.]relpath\fP" 4
Type: path ( = : ~ % )
.br
The pathname of the file relative to the start directory.

.IP "\fB[file.]dir\fP" 4
Type: path ( = : ~ % )
.br
The dirname portion of the file.

.IP "\fB[file.]name\fP" 4
Type: path ( = : ~ % )
.br
The basename portion of the file

.IP "\fB[file.]ext\fP" 4
Type: string ( = : ~ % )
.br
The file extension without the leading dot or the empty string if the file has no extension.

.IP "\fB[file.]pathx\fP" 4
Type: path ( = : ~ % )
.br
The file path without the extension.

.IP "\fB[file.]namex\fP" 4
Type: path ( = : ~ % )
.br
The file basename without the extension.

.IP "\fB[file.]mode\fP" 4
Type: mode ( = : ~ )
.br
The mode and permission bits of the file.

.IP "\fB[file.]type\fP" 4
Type: filetype ( = )
.br
The file type: one of '\fId\fP'/'\fIdirectory\fP', '\fIf\fP'/'\fIfile\fP', '\fIl\fP'/'\fIsymlink\fP', '\fIs\fP'/'\fIsocket\fP', '\fIp\fP'/'\fIpipe\fP'/'\fIfifo\fP', '\fIchar\fP', '\fIblock\fP', '\fIdoor\fP', '\fIport\fP', '\fIwhiteout\fP' or '\fIother\fP'.

.IP "\fB[file.]device\fP" 4
Type: number ( += \-= + \- = )
.br
The number of the device the file is located.

.IP "\fB[file.]inode\fP" 4
Type: number ( += \-= + \- = )
.br
The number of the inode of the file.

.IP "\fB[file.]samedev\fP" 4
Type: boolean ( = )
.br
Whether the file is on the same device as the start directory.

.IP "\fB[file.]depth\fP" 4
Type: number ( += \-= + \- = )
.br
The depth of the file relative to the start directory.

.IP "\fB[file.]exec\fP" 4
Type: boolean ( = )
.br
Whether the file is executable or not.

.IP "\fB[file.]size\fP" 4
Type: size ( += \-= + \- = )
.br
The size of the file in bytes. All types except '\fIfile\fP' have a size of 0.

.IP "\fB[file.]mtime\fP" 4
Type: time ( += \-= + \- = )
.br
The modification time of the file in seconds since epoch.

.IP "\fB[file.]ctime\fP" 4
Type: time ( += \-= + \- = )
.br
The inode change time of the file in seconds since epoch.

.IP "\fB[file.]atime\fP" 4
Type: time ( += \-= + \- = )
.br
The access time of the file in seconds since epoch.

.IP "\fB[file.]time\fP" 4
Type: time ( += \-= + \- = )
.br
An alias for '\fImtime\fP'.

.IP "\fB[file.]perm\fP" 4
Type: mode ( = : ~ )
.br
The permission bits of the file without the file type bits.

.IP "\fB[file.]links\fP" 4
Type: number ( += \-= + \- = )
.br
The number of links to the inode.

.IP "\fB[file.]uid\fP" 4
Type: number ( += \-= + \- = )
.br
The user id of the owner of the file.

.IP "\fB[file.]gid\fP" 4
Type: number ( += \-= + \- = )
.br
The group id of the owner of the file.

.IP "\fB[file.]user\fP" 4
Type: string ( = : ~ % )
.br
The user name of the owner of the file.

.IP "\fB[file.]group\fP" 4
Type: string ( = : ~ % )
.br
The group name of the owner of the file.

.IP "\fB[file.]hide\fP" 4
Type: boolean ( = )
.br
Whether the the name of the file starts with a dot.

.IP "\fB[file.]hidden\fP" 4
Type: boolean ( = )
.br
Whether the file is "hidden" or not, i.e. if one of the path components contains a leading dot.

.IP "\fB[file.]empty\fP" 4
Type: boolean ( = )
.br
Whether the file or directory is empty or not.

.IP "\fB[file.]link\fP" 4
Type: path ( = : ~ % )
.br
The target path of a symbolic link relative to its parent directory. Empty if the file is not a symbolic link.

.IP "\fB[file.]target\fP" 4
Type: path ( = : ~ % )
.br
The full target path of a symbolic link. Empty if the file is not a symbolic link.

.IP "\fB[file.]broken\fP" 4
Type: boolean ( = )
.br
Whether the target of a symbolic link points to a file that does not exist.

.IP "\fB[file.]text\fP" 4
Type: boolean ( = )
.br
Whether the file contains text or binary data.

.IP "\fB[file.]mount\fP" 4
Type: boolean ( = )
.br
Whether the entry is a mountpoint.

.IP "\fB[file.]xattrs\fP" 4
Type: listofstrings ( = : ~ % )
.br
A list of key=value pairs from the file's extended attributes.


.SH ELF PLUGIN

.SS Description
The "elf" plugin provides information extracted from ELF executable files. It requires the '\fIpyelftools\fP' module.

.SS Attributes
.IP "\fBelf.sonames\fP" 4
Type: listofstrings ( = : ~ % )
.br
The names of all shared objects that are linked in this executable file.


.SH FS PLUGIN

.SS Description
The "fs" plugin provides information on the filesystem that a file is located in.

.SS Attributes
.IP "\fBfs.type\fP" 4
Type: string ( = : ~ % )
.br
The name of the type of file system.

.IP "\fBfs.remote\fP" 4
Type: boolean ( = )
.br
Whether the file system is a remote file system.


.SH GIT PLUGIN

.SS Description
The "git" plugin provides information about files that are inside a \fBgit\fP(1) repository.

.SS Attributes
.IP "\fBgit.tracked\fP" 4
Type: boolean ( = )
.br
Whether the file is tracked by a git repository.


.SH GREP PLUGIN

.SS Description
The "grep" plugin provides access to the lines and the line count of a text file. It is useful for finding files that contain certain lines or certain substrings.

.SS Attributes
.IP "\fBgrep.linecount\fP" 4
Type: number ( += \-= + \- = )
.br
The number of lines in the file.

.IP "\fBgrep.lines\fP" 4
Type: listofstrings ( = : ~ % )
.br
The lines of the file.


.SH IGNORE PLUGIN

.SS Description
The "ignore" plugin shows whether files match patterns from .(git|fd|ff)ignore files. It is useful e.g. inside working copies of git repositories.

.SS Attributes
.IP "\fBignore.ignored\fP" 4
Type: boolean ( = )
.br
Whether the file matches patterns in a .(git|fd|ff)ignore file.

.IP "\fBignore.path\fP" 4
Type: string ( = : ~ % )
.br
The path to the ignore file that contained the matching pattern.


.SH MEDIUM PLUGIN

.SS Description
The "medium" plugin provides access to information from media files like image, audio and video files, e.g. image format, running time, mp3 tags, etc. It requires the '\fIpymediainfo\fP' module.

.SS Attributes
.IP "\fBmedium.duration\fP" 4
Type: duration ( += \-= + \- = )
.br
The duration of a medium (audio, video) in seconds.

.IP "\fBmedium.artist\fP" 4
Type: string ( = : ~ % )
.br
The artist audio tag of the file.

.IP "\fBmedium.album\fP" 4
Type: string ( = : ~ % )
.br
The album audio tag of the file.

.IP "\fBmedium.title\fP" 4
Type: string ( = : ~ % )
.br
The title audio tag of the file.

.IP "\fBmedium.genre\fP" 4
Type: string ( = : ~ % )
.br
The genre audio tag of the file.

.IP "\fBmedium.date\fP" 4
Type: string ( = : ~ % )
.br
The date audio tag of the file.

.IP "\fBmedium.format\fP" 4
Type: string ( = : ~ % )
.br
The format of an image ('\fIpng\fP', '\fIjpeg\fP', etc.) in case the file is an image.

.IP "\fBmedium.width\fP" 4
Type: number ( += \-= + \- = )
.br
The width of a visual medium (image, video) in pixel.

.IP "\fBmedium.height\fP" 4
Type: number ( += \-= + \- = )
.br
The height of a visual medium (image, video) in pixel.


.SH MIME PLUGIN

.SS Description
The "mime" plugin provides information about the content type of files. It uses '\fIlibmagic\fP' to guess the mime type and encoding. It requires the '\fIfile\-magic\fP' module.

.SS Attributes
.IP "\fBmime.mime\fP" 4
Type: string ( = : ~ % )
.br
The full mime type of the file.

.IP "\fBmime.type\fP" 4
Type: string ( = : ~ % )
.br
The content type of the file, i.e. the first part of the mime type.

.IP "\fBmime.subtype\fP" 4
Type: string ( = : ~ % )
.br
The sub type of the file, i.e. the second part of the mime type.

.IP "\fBmime.encoding\fP" 4
Type: string ( = : ~ % )
.br
The encoding of the file.

.IP "\fBmime.name\fP" 4
Type: string ( = : ~ % )
.br
The full text description of the type of the file.


.SH PACMAN PLUGIN

.SS Description
The "pacman" plugin provides information about which files were installed using the package manager pacman on an Arch Linux. It requires the '\fIpacman\fP' executable.

.SS Attributes
.IP "\fBpacman.installed\fP" 4
Type: boolean ( = )
.br
Whether the file belongs to an Arch Linux system package installed by the package manager pacman.

.IP "\fBpacman.pkgname\fP" 4
Type: string ( = : ~ % )
.br
Name of package the file belongs to.


.SH PY PLUGIN

.SS Description
The "py" plugin provides information about Python scripts.

.SS Attributes
.IP "\fBpy.imports\fP" 4
Type: listofstrings ( = : ~ % )
.br
A list of module and package names that are imported in a Python file.


.SH SHEBANG PLUGIN

.SS Description
The "shebang" plugin extracts the shebang line from a script, i.e. the first line of the file if it starts with '\fI#!\fP'.

.SS Attributes
.IP "\fBshebang.shebang\fP" 4
Type: string ( = : ~ % )
.br
The contents of the shebang line (#!).


.SH TAR PLUGIN

.SS Description
The "tar" plugin provides information about tar archives. It is useful for finding file names inside tar archives. It currently uses the tarfile module from the Python Standard Library which limits the supported compression methods to \fBgzip\fP(1), bzip2(1), \fBxz\fP(1) and uncompressed.

.SS Attributes
.IP "\fBtar.members\fP" 4
Type: listofstrings ( = : ~ % )
.br
The list of file names that are stored in a .tar archive.


