#!/bin/bash

# Fail if there is nothing to commit. (This does not work in case there are
# only new files added.)
if git diff --quiet; then
    echo "nothing to commit." >&2
    exit 0
fi

# Fail on the first failing command.
set -e

branch="$(git branch --show-current)"

if git status --short --untracked=no | grep --quiet '^ff$\|\.py$'; then
    # If on master and code has changed, increment the version number in
    # __version__.py.
    if [[ $branch = master ]]; then
        oldver=$(git show master:libff/__version__.py | grep ^__version__ | cut -d = -f 2)
        newver=$((oldver + 1))
        sed -i "/^__version__/c\__version__ = $newver" libff/__version__.py
        git add libff/__version__.py
        echo "fixing version number $oldver -> $newver"
    fi

    # Run pylint and the unittests.
    make check

    # Sort imports.
    ff -HI name=ff or ext=py -X isort -ls -m2
fi

# Update the manpage.
make -C doc
git add doc/ff.1

# The pre-commit hook disallows using "git commit" and circumventing this
# script. Tell it that it is okay to commit.
export COMMIT_ACTIVE=yes

exec git commit "${@:--av}"
