#!/bin/sh
# Run ff in debug mode, i.e. with -O off. Don't show debug messages but run all
# assert statements.

PYTHONPATH=$(dirname "$0")/.. exec python -m libff --debug none --no-parent-ignore "$@"
